### ISSUE TITLE
Socket Errorr when setting SERVER_HOST

### ISSUE THREAD

**Issue by franknitty69** [yorek/ssis-dashboard#10]
ssis-dashboard works fine on localhost. But if i set SERVER_HOST to anything and start ssis-dashboard i get the following error:

Traceback (most recent call last):
  File "app.py", line 38, in <module>
    app.run(HOST, PORT, threaded=True)
  File "c:\Python27\lib\site-packages\flask\app.py", line 843, in run
    run_simple(host, port, self, *_options)
  File "c:\Python27\lib\site-packages\werkzeug\serving.py", line 677, in run_sim
ple
    s.bind((hostname, port))
  File "c:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(_args)
socket.error: [Errno 10049] The requested address is not valid in its context

This is with Python 2.7.12 and windows server 2012.

**Comment by yorek** [comment]
It may be too late, so you may already figured out how to solve the problem (sorry for that), but I've just tried to repro the problem (now using the latest version released), and I cant...it just works, even specifying an IP address:

```
set SERVER_HOST=192.168.142.128
python runserver.py
```
