### ISSUE TITLE
Have to restart every 10 minutes

### ISSUE THREAD

**Issue by michaelclarkHID** [yorek/ssis-dashboard#17]
I have noticed with v 0.6.4, the service will stop and need to be restarted very frequently.  Is there something I can do to prevent this?

**Comment by michaelclarkHID** [comment]
added threaded=True back to the runserver.py

**Comment by yorek** [comment]
Should I go on and merge your pull? It looks like it fixes the issue.

**Comment by yorek** [comment]
Fixed by 3ee7cbf187f83305033eacf27e9f667f4a920bb3
