### ISSUE TITLE
Dockerize

### ISSUE THREAD

**Issue by cosmocracy** [yorek/ssis-dashboard#22]
Consider creating a docker container for ssis-dashboard.  This would allow teams to instantly spin up a fully-capable instance and all dependencies (Python, etc.) without having to install directly into a host.

**Comment by cosmocracy** [comment]
As part of a technical spike at our organization I'd be interested in collaborating/contributing this if time (and interest on the part of the author) allows.

**Comment by yorek** [comment]
That's a great idea! I created a docker branch and I started to build a Dockerfile. Please feel free to contribute, I'm not a docker expert so any help is welcome.

**Comment by yorek** [comment]
the problem I'm facing now is how to allow the user to write the config.cfg file and have docker container use it

**Comment by cosmocracy** [comment]
I’ll elaborate more when I get in the office but there’s a good pattern to follow that involves using a docker volume to make an external file appear inside the container.

**Comment by cosmocracy** [comment]
Nice work on your dockerization, @yorek!  Here's a good blog posting that describes the three major approaches to handling injection of config into a container.  The easiest--as it doesn't require changes to the codebase--involves presenting the config file into the container via a docker volume (option 3).

https://dantehranian.wordpress.com/2015/03/25/how-should-i-get-application-configuration-into-my-docker-containers/

Let me know after you've looked this over and if you'd like any assistance--looks like you're doing fantastically! -EK

**Comment by yorek** [comment]
Ok, this seems to be working fine:

`docker run -d -p 5000:5000 --name ssis-dashboard -e DASHBOARD_CONFIG=config.cfg -v C:\Work\lab\ssis-dashboard\config.cfg:/usr/src/app/dashboard/config.cfg ssis-dashboard `
 
Here's the config.cfg file I've created and mounted

```
AZURE = False
DEBUG = False
CONNECTION_STRING = {
                    "main": "DRIVER={ODBC Driver 13 for SQL Server};SERVER=172.25.248.123;DATABASE=SSISDB;UID=sa;PWD=Passw0rd!",
                    }
HOUR_SPAN = 360
AS_OF_DATE = 'NOW'
GOOGLE_ANALYTICS = None

```

**Comment by yorek** [comment]
Please let me know if it works also for you, so that I can close this PR. And thanks a lot for the links!

**Comment by yorek** [comment]
Docker runs well, problem is ODBC 13 reports some error when using the Dashboard. I'll try to switch to ODBC 17, just release, or to pymsssql instead of pyodbc

**Comment by yorek** [comment]
Fixed ODBC problem just by doing a cast :)

**Comment by cosmocracy** [comment]
Well done!! I’m excited to try this today with a colleague , @jasonweis. Will report back!

**Comment by yorek** [comment]
Done here: 572e266931de147b90149d0eb71587afdb63f02a

**Comment by yorek** [comment]
Will merge into master as soon I've finished some tests and cleanup
