### ISSUE TITLE
Unable to start the flask application : Error : pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC SQL Server Driver]Login timeout expired (0) (SQLDriverConnect)')

### ISSUE THREAD

**Issue by Raveendiran-RR** [yorek/ssis-dashboard#36]
Hi,

I get this error 
pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC SQL Server Driver]Login timeout expired (0) (SQLDriverConnect)')

my config :
CONNECTION_STRING = {
                    "main": "DRIVER={SQL Server};SERVER=BPTBLR0135;DATABASE=SSISDB;UID=sa;PWD=***",
                    }

The same error even when I used trustedconnection=yes
Regards,
RRR

**Comment by yorek** [comment]
That's a networking or authentication problem. Make sure server BPTBLR0135 is reachable, configured to allow external connections (check firewall settings) and that TCP support is enabled. 
Is BPTBLR0135 running on-premises or in the cloud?

**Comment by Raveendiran-RR** [comment]
Thanks Yorek for the reply, However the issue was I had to type the server name as it appears in the SSMS connection(ServerName\SQLInstanceName) and it worked

Regards
RRR
