### ISSUE TITLE
Running as a service

### ISSUE THREAD

**Issue by danbuntu** [yorek/ssis-dashboard#9]
Hello
This project is very cool. I got it running in seconds with your instructions

I'm not very familiar with python. Is there a simple way to have it run as a service rather than in a command prompt?

Dan

**Comment by yorek** [comment]
Hi Dan

it is possible, you can find details here: http://stackoverflow.com/questions/32404/is-it-possible-to-run-a-python-script-as-a-service-in-windows-if-possible-how

Enjoy!
